<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>als</string>
   </array>
  <key>name</key>
  <string>Alloy</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.Alloy</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.Alloy</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.Alloy</string>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.Alloy</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(/\*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.Alloy</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.Alloy</string>
          <key>end</key>
          <string>(\*/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.Alloy</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\bpred\b|\bopen\b|\bfor\b|\bas\b|\bfun\b|\babstract\b|\bcheck\b|\bsig\b|\bmodule\b|\bone\b|\bno\b|\bextends\b|\blone\b|\bset\b|\bexh\b|\bsome\b|\benum\b|\bfact\b|\bprivate\b|\ball\b|\belse\b|\bin\b|\bor\b|\bpred\b|\bimplies\b|\brun\b|\bthis\b|\band\b|\blet\b|\bnot\b|\bexpect\b|\buniv\b|\bassert\b|\bdisj\b|\bdisjoint\b|\bexactly\b|\bexhaustive\b|\biff\b|\bint\b|\bInt\b|\bnone\b|\bbut\b|\biden\b|\bpart\b|\bpartition\b)</string>
          <key>name</key>
          <string>storage.Alloy</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(//.*)</string>
          <key>name</key>
          <string>comment.Alloy</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(--.*)</string>
          <key>name</key>
          <string>comment.Alloy</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^_a-zA-Z0-9\x{0022}\x{0027}])</string>
          <key>name</key>
          <string>constant.Alloy</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\d*)</string>
          <key>name</key>
          <string>constant.numeric.Alloy</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
  </dict>
</dict>
</plist>
